### ISSUE TITLE
Prelude for benchmarks?

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda-ocaml#2]
The benchmarks have a dependency on a `Prelude` somewhere. I tried downloading [this one](https://github.com/UlfNorell/agda-prelude) and adding it to my default libraries, but I think it has unsupported features, since running `stack exec agda-ocaml-bench` yields

```
Compiling Mlf /agda-ocaml: unexpected number of arguments
CallStack (from HasCallStack):
  error, called at src/full/Agda/Compiler/Malfunction/Compiler.hs:350:17 in agda-ocaml-0.2.0.0-2uhJStx2q5SGsunsMGF5Mf:Agda.Compiler.Malfunction.Compiler
```

It's possible I just set something up incorrectly somewhere, but a lot of small examples I made myself seem to work.

**Comment by fredefox** [comment]
It can't be stressed enough that this is a very experimental backend. With that out of the way though it surprises me that the benchmarks aren't working for you. I suppose it could have something to do with the version of agda and/or agda-prelude.

But yes, the benchmarks use the agda-prelude you linked.

**Comment by fredefox** [comment]
ah - but of course the agda-version is controlled stack.yaml. For reference my current version of agda-prelude is `2e3addb9a434ed121805fa571f1dd0a077076a29`

**Comment by fredefox** [comment]
I've re-cloned this repo and am now trying to rebuild and run a-fresh with the most up-to-date version of agda-prelude (f9133531e0387192cb3b6569e4c05607fde80a12). Will report back. Perhaps @janmasrovira has an idea what might be amiss.

**Comment by fredefox** [comment]
I've updated the README with the reference to agda-prelude.

**Comment by fredefox** [comment]
The bencmarks are running happily on my computer.

If you are just interested in the results we wrote a short report about our results. Available [here](report).

[report]: https://gitlab.com/janmasrovira/agda2mlf/blob/master/presentation/report.org

**Comment by xekoukou** [comment]
@fredefox  Wrong link.

**Comment by fredefox** [comment]
Here's the correct link for the [report].

[report]: https://gitlab.com/janmasrovira/agda2mlf/blob/master/presentation/report.org

**Comment by identicalsnowflake** [comment]
Huh, I wonder what the problem could be. I've tried playing around with a lot of things, but always get the same thing trying to compile Prelude. Currently, stack seems to be broken (I'm getting "Access Denied" when trying to do anything), so I'll just let it be for now.

Is this backend experimental only? Or are there intentions to make a serious compile target? I've only just heard of Malfunction recently, but after watching their video, it seems like the perfect compile target.

**Comment by fredefox** [comment]
For the "intentions" you should probably ask someone else. We did this as a small project at the university of Chalmers. I just uploaded it here to give back to the community.

You could check out the report I linked. It describes the results we got and briefly mentions some of the limitations of the current implementation. Specifically there is a limited support for the Agda pragma `COMPILED` that essentially lets you map agda-postulates to the host languages. It should however be fairly easy to add support for this. I can point you in the right direction if you (or anyone else) are interested in having a go at this.

**Comment by identicalsnowflake** [comment]
You never know, [sometimes student projects get out of hand](https://en.wikipedia.org/wiki/Linux)!

I did read your report. I think part of it depends on how serious malfunction itself is: as I understand (I don't know much about OCaml; in fact, this is my first experience with it), it's using part of their internal representation, which [had a breaking change even from 4.03 to 4.04](https://github.com/stedolan/malfunction/issues/11). If malfunction updates are always that quick, there's certainly no issue, but if it was just intended as a cool side project, it could be bad news, since that internal flambda representation has (afaik) no stability guarantees, so it will bitrot very quickly.

**Comment by identicalsnowflake** [comment]
Also, if you have any information about `COMPILED` pragmas, I'd be interested in reading that. I haven't used them recently, but last time I did, I remember it having stuff like valid syntax checking, which seems like a lot of work!

**Comment by fredefox** [comment]
The `COMPILE` pragma is just a way to tell the Agda compiler that whatever you put there needs to be passed to whichever backend you'd use. So for example you'd write:

    {-# COMPILE OCaml putStrLn (global $Pervasives $print_string) #-}

But as it stands right now there is not support for this. Though adding that support shouldn't be too difficult. Currently we've just hardcoded some values into [Primitive.hs](https://github.com/agda/agda-ocaml/blob/master/src/full/Agda/Compiler/Malfunction/Primitive.hs). To add support for this you'd probably start by modifiying [AST.Term](https://github.com/agda/agda-ocaml/blob/master/src/full/Agda/Compiler/Malfunction/AST.hs#L134) to have some "verbatim" node.

I'd propose migrating this to a separate issue.

As to the long term stability of malfunction perhaps @stedolan can be of more help.
