### ISSUE TITLE
Replace dependencyGraph with info from Defn.

### ISSUE THREAD

**Issue by xekoukou** [agda/agda-ocaml#4]
We need to replace [dependencyGraph](https://github.com/agda/agda-ocaml/blob/e38b699870ba638221828b07b12948d70a1bdaec/src/full/Agda/Compiler/Malfunction/Compiler.hs#L558) with information already given by [Defn](https://github.com/agda/agda/blob/c14f2336baee03edd981641f3d78b22d19faa45a/src/full/Agda/TypeChecking/Monad/Base.hs#L1600)

**Comment by fredefox** [comment]
If I recall correctly we added the dependency graph-thingy because we do whole-module compilation. @janmasrovira correct me if I'm wrong.

**Comment by xekoukou** [comment]
Is it even possible to have mutual recursion from two different modules? I
think this is not possible, so it is safe even for whole-module compilation.

**Comment by fredefox** [comment]
Ah yes of course. Then I dont remember why we introduced it.

**Comment by xekoukou** [comment]
I will make the changes. (I expect the test system to not work for some time. I have changed the command line interface so as to perform agda's compiler tests.)

**Comment by xekoukou** [comment]
```FunMutual``` is only updated on mutual blocks, it seems.
